### ISSUE TITLE
ReDiscovery - Schwarzer Text auf schwarzem Hintergrund bei register & pwforgot

### ISSUE THREAD

**Issue by yaench** [etoa/etoa-gui#549]
Wenn im Admin-Tool als Standard Design "Rediscovery" konfiguriert wird, ist der Text bei den Seiten "register" und "pwforgot" schwarz auf schwarzem Hintergrund und somit nicht lesbar.

Setze ich lokal im Browser in "/htdocs/designs/official/Rediscovery/style.css" für Body "color:white;" ist die Schrift lesbar.

**Comment by yaench** [comment]
Update: In Runde 23 habe ich manuell in der Datei "/var/www/etoa/htdocs/web/css/external.css" color und font-family hinzugefügt, nun zeigt es bei register & pwforgot den Text korrekt an.
```css
#outGameContent	{
	margin: 80px auto 10px;
	width: 800px;	
	color: white;
	font-family: Verdana, sans-serif;
}
```
